# This is a basic workflow to help you get started with Actions

name: Cron Job Deploy Server

# Controls when the workflow will run
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install python version
      - name: Setup Python Version
        uses: actions/checkout@v3
        with:
          python-version: 3.8 # Install the python version needed

      # Install python dependency
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"

      # Execute python
      - name: Execute Python script # Run the DigitalCV_CourseRecommendation_AssociationRule.py
        run: python zipfile.py
